version: '3.8'

services:
  fastapi_app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      APP_ENV: ${APP_ENV}
      DEFAULT_API_VERSION: ${DEFAULT_API_VERSION}
      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: unless-stopped
    networks:
      - openbayanmesh-network

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_DATABASE: ${NEO4J_DATABASE}
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD} # Required for init scripts to work
    volumes:
      - neo4j_data:/data
      - ./neo4j_init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - openbayanmesh-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yaml run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
      TUNNEL_ID: ${TUNNEL_ID}
    volumes:
      - ./cloudflared:/etc/cloudflared
    restart: unless-stopped
    networks:
      - openbayanmesh-network
    depends_on:
      - fastapi_app

networks:
  openbayanmesh-network:
    driver: bridge

volumes:
  neo4j_data:
